export const ToolbarStyle = {  display: "flex",
justifyContent: "space-between",
alignItems: "center",
padding: "0",
margin: "0",
color: "#667085",
fontWeight: "bold",
textTransform: "none",
minHeight: "fit-content !important",
}